// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ1hK4HYPM1tQEw_irHQFxHm_LwdwgOrk',
    appId: '1:645482868327:web:afd98aa06b7264e1a7aec2',
    messagingSenderId: '645482868327',
    projectId: 'chatapp-5b5cb',
    authDomain: 'chatapp-5b5cb.firebaseapp.com',
    storageBucket: 'chatapp-5b5cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDerKM57MbtwWNDAuU7QI7jOysO_12YIL8',
    appId: '1:645482868327:android:72c7cae77d738a4aa7aec2',
    messagingSenderId: '645482868327',
    projectId: 'chatapp-5b5cb',
    storageBucket: 'chatapp-5b5cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxjxr4ZQI8CRTp2YeXXh4npmA8ioOTqoM',
    appId: '1:645482868327:ios:ca5ca2466dbd8478a7aec2',
    messagingSenderId: '645482868327',
    projectId: 'chatapp-5b5cb',
    storageBucket: 'chatapp-5b5cb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxjxr4ZQI8CRTp2YeXXh4npmA8ioOTqoM',
    appId: '1:645482868327:ios:ca5ca2466dbd8478a7aec2',
    messagingSenderId: '645482868327',
    projectId: 'chatapp-5b5cb',
    storageBucket: 'chatapp-5b5cb.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ1hK4HYPM1tQEw_irHQFxHm_LwdwgOrk',
    appId: '1:645482868327:web:4fe4bdab1d92fe12a7aec2',
    messagingSenderId: '645482868327',
    projectId: 'chatapp-5b5cb',
    authDomain: 'chatapp-5b5cb.firebaseapp.com',
    storageBucket: 'chatapp-5b5cb.appspot.com',
  );

}